### ISSUE TITLE
Create primary content template

### ISSUE THREAD

**Issue by andreysakhno** [andreysakhno/homepage#17]
**1. Add a content template**
```html
<main>
  <div class="resume">
    <div class="container">
      <div class="resume__block">
        <h1 class="contact-info__header">Bulka</h1>
        <h3 class="contact-info__sub-header">Senior Hooman Manager</h3>

        <div class="contact_info_container fh">
          <div class="contact-info__block"></div>
        
          <div class="contact-info__block contact-info__block--center">
            <img class="contact-info__avatar" src="assets/avatar.png" alt="Avatar">
          </div>

          <div class="contact-info__block"></div>
        </div>
      </div>
    </div>
  </div>
</main>
``` 
**2. Create assets folder and put here any Bulka's image from his [Instagram]. Use it as a src= for avatar.**

**Comment by andreysakhno** [comment]
**- flex-box horizontal**
```css
.fh {
   display: flex;
   flex-direction: row;
   justify-content: space-between;
}
``` 

**- flex-box vertical**
```css
.fv {
   display: flex;
   flex-direction: column;
   justify-content: space-between;
}
```
